# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f336ca2d752e76e31c3ca74ee86e4beb217be260932113498ab77a6fd2c00b885f208e7c1b7102abc8589e542c189a922b60bba6b6586197b9708ae74f128cbc

test:
  secret_key_base: 2f8baa07a6bc132b811f0d32d9092d7dfcbd1b4e504f0cb0810309f87457e7dfacbee25f010acc6c96d77b5209d9082fe3510df36474188cf3c73b4fcb069d87

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
